Admin/urls.py
from unicodedata import name
from django import views
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from Admin import Lectureview, views ,Revanueview
from Admin.views import Home
#from django.conf.urls import url
app_name = "Admin"

urlpatterns = [
    path('', views.Home , name='Home'),
    path('AHome', views.Home , name='AHome'),
    # lecture
    path('Lectureboard', Lectureview.Lectureboard , name='Lectureboard'),
    path('Addlecture', Lectureview.Lectures , name="Addlecture"),
    path('Lecture_edit/<int:id>/', Lectureview.Lecture_edit , name='Lecture_edit'),
    path('Leature_delete/<int:id>/', Lectureview.Leature_delete , name='Leature_delete'),
    # lecture
    
    # course
    path('Courseboard', views.Courseboard , name='Courseboard'),
    path('Addcourse', views.Addcourse , name='Addcourse'),
    path('Course_edit/<int:id>/', views.Course_edit , name='Course_edit'),
    path('Course_delete/<int:id>/', views.Course_delete , name='Course_delete'),
    # course
    
    # add teacher
    path('Addteacher', views.Addteacher , name='Addteacher'),
    path('Addteacherdetail', views.Addteacherdetail , name='Addteacherdetail'),
    # add teacher
    
    path('AdminProfile', views.Profile , name='AdminProfile'),
    path('Revenue', Revanueview.Revenue , name="Revenue"),
    path('paymentlist', Revanueview.paymentlist , name="paymentlist"),
    path('duelist', Revanueview.duelist , name="duelist"),

    # add student
    
    path('Studentboard', views.Studentboard , name="Studentboard"),
    path('Student_edit/<int:id>/', views.Student_edit , name="Student_edit"),
    path('Student_delete/<int:id>/', views.Student_delete , name="Student_delete"),
    path('Addstudent', views.Addstudent , name="Addstudent"),
    path('ADDstudent', views.ADDstudent , name="ADDstudent"),
    
    # path('Recheck', views.Student_Admission_recheck , name='Recheck' ),
    # add student
    
    # revenue
    # path('Revenue',revenueviews.revenue,name='Revenue'),
    # path('Todays_Revenue',revenueviews.Todays_Revenue,name='Todays_Revenue'),
    # path('totalrevenue',revenueviews.totalrevenue,name='totalrevenue'),
    
   

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

BRD/urls.py
from django.contrib import admin
from django.urls import path,include
#from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
# import notifications.urls

from django.conf.urls import include
from django.views.generic.base import TemplateView
from django.contrib.auth import views as auth_views
from Admin import views
admin.site.site_header = 'Student Admission'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include( 'Home.urls')),
    path('',include( 'Student.urls')),
    path('',include( 'Teacher.urls')),
    path('',include( 'Admin.urls')),
    path('accounts/',include ('accounts.urls')),
    path('robots.txt',TemplateView.as_view(template_name="Base/robots.txt", content_type="text/plain")),
    path(r'^$',views.handler404, name='handler404'),
    #url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    # url('', include('social_django.urls', namespace='social')),
    #  path('forest', include('django_forest.urls')),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),name='password_reset_complete'),
    # url('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
handler404= 'Admin.views.handler404'

Home/urls.py
from unicodedata import name
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf import settings
from django.conf.urls.static import static
from  Home import views
from django.views.static import serve


app_name = "Home"

urlpatterns = [
    # path('Student_Admission', views.Student_Admission , name='Student_Admission'  ),
    path('', views.Home  ),
    path('Base', views.Home , name="Base" ),
    path('Home', views.Home , name="Home" ),
    path('email_Data', views.email_Data , name="email_Data" ),
    path('Online-Admission', views.Addstudent , name="Online-Admission" ),
    path('About-Us', views.About , name="About-Us" ),
    path('ContactUs', views.ContactUs , name="ContactUs" ),
    path('Term-and-condition', views.TAC , name="Term-and-condition" ),
    path('Refund-&-Cancellation', views.TAC2 , name="Refund-&-Cancellation" ),
    path('allcourse/', views.allcourse.as_view(), name='allcourse'),
    path('privacypolicy', views.privacypol , name="privacypolicy" ),	
    path('coursedetailview/<slug>', views.coursedetailview.as_view(), name='coursedetailview'),
    path('blogdetailview/<slug>', views.blogdetailview.as_view(), name='blogdetailview'),
    path('eventdetailview/<slug>', views.eventdetailview.as_view(), name='eventdetailview'),
    path('blogpage/',views.blogpage.as_view(),name='blogpage'),



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, }),


]

Home/models.py
from email import message
from django.db import models
from ckeditor.fields import RichTextField
from autoslug import AutoSlugField


# Create your models here.
class query_form(models.Model):
    form_name = models.CharField(max_length=100,null=True)
    form_email = models.CharField(max_length=100,null=True)
    form_subject = models.CharField(max_length=100,null=True)
    form_message = models.CharField(max_length=1000,null=True)
    created = models.DateTimeField(auto_now_add=True,null=True)


    def __str__(self):
        return self.form_subject


class slider(models.Model):
    slider_name = models.CharField(null=True , max_length = 50 )
    slider_img = models.ImageField(upload_to='static/slider', null=True ,max_length = 100)
    Details = RichTextField(blank=True , null=True)
    
    def __str__(self):
        return self.slider_name
    
    
class q_form(models.Model):
    name = models.CharField(max_length=50,null=True)
    email = models.EmailField( max_length=254 , null=True) 
    phone = models.CharField(max_length=15 , null=True)
    message = models.CharField( max_length=500, null=True)
    subject = models.CharField(max_length=100,null=True)
       
       
class email_data(models.Model):
    email = models.EmailField( max_length=254 , null=True)       
    def __str__(self):
        return self.email


class blog(models.Model):
    blog_title = models.CharField(max_length=300, null=True)
    blog_img = models.ImageField(blank=True, upload_to='media')
    blog_desp = RichTextField()
    blog_date = models.DateField(auto_now_add=False)
    blog_author = models.CharField(max_length=30,null=True)
    blog_slug = AutoSlugField(populate_from='blog_title',unique=True ,default=None, blank=False, null=True)

class Course(models.Model):
    course_img = models.ImageField(upload_to='media', blank=False)
    course_bann = models.ImageField(upload_to='media', blank=False,null=True)
    course_price = models.CharField(max_length=6, null=True)
    course_title = models.CharField(max_length=50,null=True, blank=False)
    course_descp = RichTextField(blank=False, null=False)
    course_stu = models.CharField(max_length=5,null=True)
    course_lessons = models.CharField(max_length=4, null=True)
    course_slug = AutoSlugField(populate_from='course_title',unique=True ,default=None, blank=False, null=True)

class StuReview(models.Model):
    stu_name = models.CharField(max_length=40, null=True)
    stu_descp = models.CharField(max_length=500,null=True)

class Event(models.Model):
    event_title = models.CharField(max_length=200,null=True, blank=False)
    event_img = models.ImageField(upload_to='media', blank=False)
    event_descp = RichTextField(blank=False, null=False)
    event_date = models.DateField(auto_now_add=False)
    event_time = models.TimeField(auto_now_add=False)
    event_location = models.CharField(max_length=30,null=True)
    event_slug = AutoSlugField(populate_from='event_title',unique=True ,default=None, blank=False, null=True)

Home/views.py
from django.shortcuts import redirect, render,HttpResponseRedirect
from django.urls import reverse
from Student.forms import Student_detailForm
from Home.models import *
import sweetify
from django.views import View
from django.shortcuts import HttpResponse
from django.contrib import messages
# Create your views here.


def Home(request):
    course = Course.objects.all().order_by('id').reverse()[0:3]
    stur = StuReview.objects.all().order_by('id').reverse()
    eve = Event.objects.all().order_by('id').reverse()
    return render(request, 'Home/index.html',{'course':course,'stur':stur,'eve':eve})


def email_Data(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        emaildata = email_data.objects.create(email=email)
        emaildata.save()
        messages.info(request,"Successfully Submitted")
        # sweetify.success(request, 'Hey', text= 'You have successfully Subscribed', persistent='Done')
        return redirect('Home:Home')
        

def Addstudent(request):
    form = Student_detailForm()
    context = {
        'form':form
    }
    return render(request, 'Home/Addstudent.html' , context)
def About(request):
    return render(request, 'Home/about.html')

def ContactUs(request):
    if request.method == "POST":
        name = request.POST.get('name')
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        subject = request.POST.get('subject')
        qform = q_form.objects.create(name = name , email=email , phone = phone , message = message,subject=subject)
        qform.save()
        messages.info(request,"Successfully Submitted")
        # sweetify.success(request, 'Hey', text= 'You have successfully filled the form', persistent='Done')
        return HttpResponseRedirect(reverse('Home:ContactUs'))
    return render(request, 'Home/contactUs.html')

class blogpage(View):
    def get(self,request):
        bl = blog.objects.all()
        return render(request, 'Home/blog.html', {'bl':bl })

class blogdetailview(View):
    def get(self,request,slug):
        Blog = blog.objects.get(blog_slug=slug)
        Blog_object=blog.objects.get(blog_slug=slug)
        Blog_object.save()

        return render(request, 'Home/blogdetail.html',{'Blog':Blog})

class eventdetailview(View):
    def get(self,request,slug):
        event = Event.objects.get(event_slug=slug)
        event_object=Event.objects.get(event_slug=slug)
        event_object.save()

        return render(request, 'Home/eventdetail.html',{'event':event})

def TAC(request):
    return render(request, 'Home/titan.html')
def TAC2(request):
    return render(request, 'Home/TAC.html')

class allcourse(View):
    def get(self,request):
        course = Course.objects.all().order_by('id').reverse()[0:6]
        return render(request, 'Home/allcourse.html', {'course':course})

class coursedetailview(View):
    def get(self,request,slug):
        course = Course.objects.get(course_slug=slug)
        course_object=Course.objects.get(course_slug=slug)
        course_object.save()

        return render(request, 'Home/coursedetail.html',{'course':course})

def privacypol(request):
    return render(request, 'Home/privacypolicy.html')

templates/Home/Addstudent.html
{% extends 'Base/homebase.html' %} {% block title %} Admission {%endblock %} {%
block metadescription %} {% block body %}

<div class="page-banner-area bg-2">
  <div class="container">
    <div class="page-banner-content">
      <h1 style="text-align: center;">Online Addmission</h1>
      
    </div>
  </div>
</div>

<!-- online addmission forms section -->

<div class="py-5" style="background-image: linear-gradient(to bottom right, #e6f6fa, #f0f8fa);">
  <div class="container">
    <div class="addmission-form-box">
      <div class="addmission-header text-center mb-5">
        <h5>Let's Get Started</h5>
      </div>
      <form
        enctype="multipart/form-data"
        method="post"
        class="row"
        action="{% url 'Admin:ADDstudent' %}"
      >
        {% csrf_token %}
        <div class="row">
          {% for fm in form %}

          <div class="col-md-6 my-2">
            <p>{{fm.label_tag}}</p>
            {{ fm }} {{ fm.errors }}
          </div>
          {% endfor %}
        </div>
        <div>
          <input type="checkbox" required />
          <a
            href="{% url 'Home:Term-and-condition' %}"
            style="text-decoration: none"
            >Terms & Conditions*</a
          >
        </div>
        <button type="submit" class="mt-5" style="border: none; color: white; background-color: #19a5e0;padding: 7px; margin-right: 85%;">SUBMIT</button>
      </form>
    </div>
  </div>
</div>

{% endblock %}

templates/Home/TAC.html
{% extends 'Base/homebase.html' %} {% block title %} Refund & Cancellation {%
block metadescription %} {% endblock %} {% block body %}
<section class="page-banner">
  <div
    class="page-banner-bg bg_cover"
    style="background-image: url(/static/Home/images/page-banner.webp)"
  >
    <div class="container">
      <div class="banner-content text-center">
        <h2 class="title">Refund & Cancellation</h2>
      </div>
    </div>
  </div>
</section>

<div class="container mt-5 mb-5">
  <div class="title-div">
    <h3 class="tittle"><span>R</span>efund &amp; <span>C</span>ancellation</h3>
    <div class="tittle-style"></div>
  </div>
  <div class="about-sub">
    <div class="col-md-12 about_bottom_left">
      <p>
        We at Titan Aviation  are committed to provide the best courses
        on aviation &amp; hospitality.
      </p>
      <p>
        It’s our top priority that business transactions between us are
        completely transparent. Since our online courses are immediately
        available after purchase. Therefore, we have “NO REFUND POLICY”
      </p>
      <p>
        In case of dissatisfaction from the course, you are encouraged to write
        about your particular concerns with us at our email ( info@Avis
        Academy.in ). We will take all possible measures to address your
        concern.
      </p>
    </div>
  </div>
</div>

{% endblock %}

templates/Home/about.html
{% extends 'Base/homebase.html' %} {% block title %}Best Aviation
Management Institute | Titan Aviation{% endblock %}{% block metadescription %}
<meta name="description" content="" />
<meta name="tittle" content="" />
<meta name="keywords" content="" />
{% endblock %} {% block body %}
<!-- Main content Start -->
<div class="main-content">
<!-- Breadcrumbs Start -->
<div class="rs-breadcrumbs breadcrumbs-overlay">
   <div class="breadcrumbs-img">
      <img src="/static/Home/assets/images/breadcrumbs/2.jpg" alt="Breadcrumbs Image">
   </div>
   <div class="breadcrumbs-text white-color">
      <h1 class="page-title">About Us</h1>
      <ul>
         <li>
            <a class="active" href="/">Home</a>
         </li>
         <li>About Us</li>
      </ul>
   </div>
</div>
<!-- Breadcrumbs End -->
<!-- About Section Start -->
<div id="rs-about" class="rs-about style1 pt-100 pb-100 md-pt-70 md-pb-70">
   <div class="container">
      <div class="row align-items-center">
         <div class="col-lg-6 order-last padding-0 md-pl-15 md-pr-15 md-mb-30">
            <div class="img-part">
               <img class="" src="/static/Home/assets/images/about/about2orange.png" alt="About Image">
            </div>
         </div>
         <div class="col-lg-6 pr-70 md-pr-15">
            <div class="sec-title">
               <div class="sub-title orange">About Titan Aviation</div>
               <h2 class="title mb-17">Welcome to The Titan Aviation Institute</h2>
               <div class="bold-text mb-22">Many educationists and academic men have praised Titan Aviation Institute for its excellence in providing high-quality educational courses,</div>
               <div class="desc">programs, and practical vividness in the aviation industry, hotel management, and Tourism Management. Since the institute's founding, we have encouraged new ideas, technological advancement, and young entrepreneurship among all candidates in order to prepare them for careers in a competitive industry.</div>
            </div>
         </div>
      </div>
   </div>
</div>
<!-- About Section End -->
<!-- Counter Section Start -->
<div id="rs-counter" class="rs-counter style2-about pt-100 md-pt-70">
   <div class="container">
      <div class="row couter-area">
         <div class="col-md-4 sm-mb-30">
            <div class="counter-item text-center">
               <div class="counter-bg">
                  <img src="/static/Home/assets/images/counter/bg1.png" alt="Counter Image">
               </div>
               <div class="counter-text">
                  <h2 class="rs-count kplus">2</h2>
                  <h4 class="title mb-0">Students</h4>
               </div>
            </div>
         </div>
         <div class="col-md-4 sm-mb-30">
            <div class="counter-item text-center">
               <div class="counter-bg">
                  <img src="/static/Home/assets/images/counter/bg2.png" alt="Counter Image">
               </div>
               <div class="counter-text">
                  <h2 class="rs-count">8.50</h2>
                  <h4 class="title mb-0">Average CGPA</h4>
               </div>
            </div>
         </div>
         <div class="col-md-4">
            <div class="counter-item text-center">
               <div class="counter-bg">
                  <img src="/static/Home/assets/images/counter/bg3.png" alt="Counter Image">
               </div>
               <div class="counter-text">
                  <h2 class="rs-count percent">95</h2>
                  <h4 class="title mb-0">Graduates</h4>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
<!-- Counter Section End -->
<!-- About Section Start -->
<div class="rs-about style1 pt-100 pb-100 md-pt-70 md-pb-70">
   <div class="container">
      <div class="row align-items-center">
         <div class="col-lg-6 padding-0 md-pl-15 md-pr-15 md-mb-30">
            <div class="img-part">
               <img class="" src="/static/Home/assets/images/about/history.png" alt="About Image">
            </div>
            <ul class="nav nav-tabs histort-part" id="myTab" role="tablist">
               <li class="nav-item tab-btns single-history">
                  <a class="nav-link tab-btn active" id="about-history-tab" data-toggle="tab" href="#about-history" role="tab" aria-controls="about-history" aria-selected="true"><span class="icon-part"><i class="flaticon-banknote"></i></span>History</a>
               </li>
               <li class="nav-item tab-btns single-history">
                  <a class="nav-link tab-btn" id="about-mission-tab" data-toggle="tab" href="#about-mission" role="tab" aria-controls="about-mission" aria-selected="false"><span class="icon-part"><i class="flaticon-flower"></i></span>Mission & Vission</a>
               </li>
               <li class="nav-item tab-btns single-history last-item">
                  <a class="nav-link tab-btn" id="about-admin-tab" data-toggle="tab" href="#about-admin" role="tab" aria-controls="about-admin" aria-selected="false"><span class="icon-part"><i class="flaticon-analysis"></i></span>Administration</a>
               </li>
            </ul>
         </div>
         <div class="offset-lg-1"></div>
         <div class="col-lg-5">
            <div class="tab-content tabs-content" id="myTabContent">
               <div class="tab-pane tab fade show active" id="about-history" role="tabpanel" aria-labelledby="about-history-tab">
                  <div class="sec-title mb-25">
                     <h2 class="title">Titan Aviation History</h2>
                     <div class="desc">To develop Institute as a Centre of Excellence in Aviation. To inculcate in its students the qualities of Leadership, Professionalism, Executive Competence and Corporate understanding. To transform students into Globally Competitive Professionals.</div>
                  </div>
                  <div class="tab-img">
                     <img class="" src="/static/Home/assets/images/about/tab1.jpg" alt="Tab Image">
                  </div>
               </div>
               <div class="tab-pane fade" id="about-mission" role="tabpanel" aria-labelledby="about-mission-tab">
                  <div class="sec-title mb-25">
                     <h2 class="title">Titan Aviation Mission</h2>
                     <div class="desc">Ever since its commencement the institute has promoted entrepreneurship, new concepts and technological innovations among its students to create them the longer term leaders of the skilled world.Our Institute delivers the real-world experience one needs to succeed in today's competitive global marketplace.</div>
                  </div>
                  <div class="tab-img">
                     <img class="" src="/static/Home/assets/images/about/tab2.jpg" alt="Tab Image">
                  </div>
               </div>
               <div class="tab-pane fade" id="about-admin" role="tabpanel" aria-labelledby="about-admin-tab">
                  <div class="sec-title mb-25">
                     <h2 class="title">Titan Aviation Administration</h2>
                     <div class="desc">Every organization, irrespective of the industry, needs an excellent administration to organize the company. The admin department often gets unheralded in business; however, their role should not be underestimated. Without this backbone, things can instantly fall apart, making it challenging for the organization to function as intended.</div>
                  </div>
                  <div class="tab-img">
                     <img class="" src="/static/Home/assets/images/about/tab3.jpg" alt="Tab Image">
                  </div>
               </div>
            </div>
         </div>
      </div>
      <!-- Intro Info Tabs-->
      <div class="intro-info-tabs">
      </div>
   </div>
</div>
<!-- About Section End -->
<!-- Team Section Start -->
<div id="rs-team" class="rs-team style1 orange-color pt-94 pb-100 md-pt-64 md-pb-70 gray-bg">
   <div class="container">
      <div class="sec-title mb-50 md-mb-30">
         <div class="sub-title orange">Instructor</div>
         <h2 class="title mb-0">Expert Teachers</h2>
      </div>
      <div class="rs-carousel owl-carousel nav-style2 orange-color" data-loop="true" data-items="3" data-margin="30" data-autoplay="true" data-hoverpause="true" data-autoplay-timeout="5000" data-smart-speed="800" data-dots="false" data-nav="true" data-nav-speed="false" data-center-mode="false" data-mobile-device="1" data-mobile-device-nav="false" data-mobile-device-dots="false" data-ipad-device="2" data-ipad-device-nav="false" data-ipad-device-dots="false" data-ipad-device2="2" data-ipad-device-nav2="false" data-ipad-device-dots2="false" data-md-device="3" data-md-device-nav="true" data-md-device-dots="false">
         <div class="team-item">
            <img src="/static/Home/assets/images/team/1.jpg" alt="">
            <div class="content-part">
               <h4 class="name">Akhlesh</h4>
               <span class="designation">Professor</span>
            </div>
         </div>
         <div class="team-item">
            <img src="/static/Home/assets/images/team/2.jpg" alt="">
            <div class="content-part">
               <h4 class="name">Jessi</h4>
               <span class="designation">Professor</span>
            </div>
         </div>
         <div class="team-item">
            <img src="/static/Home/assets/images/team/3.jpg" alt="">
            <div class="content-part">
               <h4 class="name">Alex</h4>
               <span class="designation">Professor</span>
            </div>
         </div>
      </div>
   </div>
</div>
<!-- Team Section End -->           
<!-- Testimonial Section Start -->
<div class="rs-testimonial style2 pt-100 pb-100 md-pt-70 md-pb-70">
   <div class="container">
      <div class="row">
         <div class="col-lg-5 pr-90 md-pr-15 md-mb-30">
            <div class="donation-part">
               <img src="/static/Home/assets/images/donor/1.jpg" alt="">
               <h3 class="title mb-10">Titan Aviation helps us</h3>
               <div class="desc mb-38">Titan Aviation is the best if you want to do your diploma course in aviation industry. FIAT is well-equipped with modern facilities that are suitable for both online and offline instruction. The institute makes significant efforts to ensure that students' learning experiences are comprehensive. The best thing is that they will provide you with the hospitality, travel and tourism.</div>
               <div class="btn-part">
                  <a class="readon2 orange" href="{% url 'Home:Online-Admission' %}">Apply Now</a>
               </div>
            </div>
         </div>
         <div class="col-lg-7 lg-pl-0 ml--15 md-ml-0">
            <div class="testi-wrap mb-50">
               <div class="img-part">
                  <img src="/static/Home/assets/images/testimonial/style2/1.jpg" alt="">
               </div>
               <div class="content-part new-content pt-12">
                  <div class="desc">Education is the passport to the future for tomorrow belongs to those who prepare for it today</div>
                  <div class="info">
                     <h5 class="name">Mahadi mansura</h5>
                     <div class="designation">Head Teacher</div>
                  </div>
               </div>
            </div>
            <div class="testi-wrap">
               <div class="img-part">
                  <img src="/static/Home/assets/images/testimonial/style2/2.jpg" alt="">
               </div>
               <div class="content-part new-content pt-12">
                  <div class="desc">Education is the passport to the future for tomorrow belongs to those who prepare for it today</div>
                  <div class="info">
                     <h5 class="name">Jonathon Lary</h5>
                     <div class="designation">Math Teacher</div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
<!-- Testimonial Section End -->
{% endblock %}

templates/Home/allcourse.html
{% extends 'Base/homebase.html' %} {% block title %} Our Courses | Titan Aviation{% endblock %}
{%block metadescription %}
<meta name="description" content="" />
<meta name="tittle" content="" />
<meta name="keywords" content="" />
{% endblock %} {% block body %}


<!-- Main content Start -->
<div class="main-content">
  <!-- Breadcrumbs Start -->
  <div class="rs-breadcrumbs breadcrumbs-overlay">
      <div class="breadcrumbs-img">
          <img src="/static/Home/assets/images/breadcrumbs/1.jpg" alt="Breadcrumbs Image">
      </div>
      <div class="breadcrumbs-text">
          <h1 class="page-title">Our Courses</h1>
          <ul>
              <li>
                  <a class="active" href="/">Home</a>
              </li>
              <li>Course</li>
          </ul>
      </div>
  </div>
  <!-- Breadcrumbs End -->            

  <!-- Popular Course Section Start -->
  <div class="rs-popular-courses style2 white-bg pt-94 pb-100 md-pt-64 md-pb-70">
      <div class="container">
          <div class="row">
            {% for c in course %}
              <div class="col-lg-4 col-md-6 mb-30">
                  <div class="course-wrap">
                      <div class="front-part">
                          <div class="img-part">
                            {% if c.course_img %}
                              <img src="{{c.course_img.url}}" alt="">
                            {% endif %}
                          </div>
                          <div class="content-part">
                              <a class="categorie" href="#">Titan Aviation</a>
                              <h4 class="title"><a href="{% url 'Home:coursedetailview' c.course_slug %}">{{c.course_title}}</a></h4>
                          </div>
                      </div>
                      <div class="inner-part">
                          <div class="content-part">
                              <a class="categorie" >Titan Aviation</a>
                              <h4 class="title"><a href="{% url 'Home:coursedetailview' c.course_slug %}">{{c.course_title}}</a></h4>
                              <ul class="course-meta">
                                  <li class="course-user"><i class="fa fa-user"></i> {{c.course_stu}}</li>
                                  <li class="user"><i class="fa fa-file"></i> {{c.course_lessons}} Lessons</li>
                              </ul>
                          </div>
                      </div>
                      <div class="price-btn">
                          <a href="{% url 'Home:Online-Admission' %}">₹ {{c.course_price}} <i class="flaticon-next"></i></a>
                      </div>
                  </div>
              </div>
              {% endfor %}
              
              
          </div>
          
      </div>
  </div>
  
</div> 

{% endblock %}

templates/Home/blogdetail.html
{% extends 'Base/homebase.html' %} {% block title %}Blog | Titan Aviation{% endblock %}{% block metadescription %}
<meta name="description" content="" />
<meta name="tittle" content="" />
<meta name="keywords" content="" />
{% endblock %} {% block body %}
<style>
    .blog_details img 
    {
        width: 100%;
        height: 400px;
        object-fit: cover;
        object-position: top;
    }
</style>
<div class="main-content">
    <!-- Breadcrumbs Start -->
    <div class="rs-breadcrumbs breadcrumbs-overlay">
        <div class="breadcrumbs-img">
            {% if Blog.blog_img %}
                 <img src="{{Blog.blog_img.url}}"alt="Image" class="" height="450px">
            {% endif %}
        </div>
        <div class="breadcrumbs-text white-color">
            <h1 class="page-title">Blog</h1>
            <ul>
                <li>
                    <a class="active" href="/">Home</a>
                </li>
                <li>Blog Detail</li>
            </ul>
        </div>
    </div>

<!-- Events section  -->

<div class="events-details-area pt-100 pb-70">
    <div class="container">
        <div class="section-title">
            <h2 class="heading-icon">{{Blog.blog_title}}</h2>
        </div>
        <div class="row">
            <div class="col-lg-9">
                <div class="events-details-left-content pr-20">
                    <div class="events-image blog_details">
                        {% if Blog.blog_img %}
                         <img src="{{Blog.blog_img.url}}"alt="Image" class="">
                        {% endif %}
                    </div>
                    <div class="meetings mt-4">
                        <div style="text-align: justify;">
                            {{Blog.blog_desp | safe}}
                        </div>
                        
                    </div>
                    
                </div>
            </div>
            <div class="col-lg-3">
                <div class="p-5" style="background-color: #c3eafa;">
                    <h4 class="address"><i class="fa fa-pencil"></i> {{Blog.blog_author}}</h4>
                    <h4 class="timesec"><i class="fa fa-calendar"></i> {{Blog.blog_date}}</h4>
                </div>
            </div>

        </div>
    </div>
</div>

{% endblock %}