Admin/urls.py
from unicodedata import name
from django import views
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from Admin import Lectureview, views ,Revanueview
from Admin.views import Home
#from django.conf.urls import url
app_name = "Admin"

urlpatterns = [
    path('', views.Home , name='Home'),
    path('AHome', views.Home , name='AHome'),
    # lecture
    path('Lectureboard', Lectureview.Lectureboard , name='Lectureboard'),
    path('Addlecture', Lectureview.Lectures , name="Addlecture"),
    path('Lecture_edit/<int:id>/', Lectureview.Lecture_edit , name='Lecture_edit'),
    path('Leature_delete/<int:id>/', Lectureview.Leature_delete , name='Leature_delete'),
    # lecture
    
    # course
    path('Courseboard', views.Courseboard , name='Courseboard'),
    path('Addcourse', views.Addcourse , name='Addcourse'),
    path('Course_edit/<int:id>/', views.Course_edit , name='Course_edit'),
    path('Course_delete/<int:id>/', views.Course_delete , name='Course_delete'),
    # course
    
    # add teacher
    path('Addteacher', views.Addteacher , name='Addteacher'),
    path('Addteacherdetail', views.Addteacherdetail , name='Addteacherdetail'),
    # add teacher
    
    path('AdminProfile', views.Profile , name='AdminProfile'),
    path('Revenue', Revanueview.Revenue , name="Revenue"),
    path('paymentlist', Revanueview.paymentlist , name="paymentlist"),
    path('duelist', Revanueview.duelist , name="duelist"),

    # add student
    
    path('Studentboard', views.Studentboard , name="Studentboard"),
    path('Student_edit/<int:id>/', views.Student_edit , name="Student_edit"),
    path('Student_delete/<int:id>/', views.Student_delete , name="Student_delete"),
    path('Addstudent', views.Addstudent , name="Addstudent"),
    path('ADDstudent', views.ADDstudent , name="ADDstudent"),
    
    # path('Recheck', views.Student_Admission_recheck , name='Recheck' ),
    # add student
    
    # revenue
    # path('Revenue',revenueviews.revenue,name='Revenue'),
    # path('Todays_Revenue',revenueviews.Todays_Revenue,name='Todays_Revenue'),
    # path('totalrevenue',revenueviews.totalrevenue,name='totalrevenue'),
    
   

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

BRD/urls.py
from django.contrib import admin
from django.urls import path,include
#from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
# import notifications.urls

from django.conf.urls import include
from django.views.generic.base import TemplateView
from django.contrib.auth import views as auth_views
from Admin import views
admin.site.site_header = 'Student Admission'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include( 'Home.urls')),
    path('',include( 'Student.urls')),
    path('',include( 'Teacher.urls')),
    path('',include( 'Admin.urls')),
    path('accounts/',include ('accounts.urls')),
    path('robots.txt',TemplateView.as_view(template_name="Base/robots.txt", content_type="text/plain")),
    path(r'^$',views.handler404, name='handler404'),
    #url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    # url('', include('social_django.urls', namespace='social')),
    #  path('forest', include('django_forest.urls')),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),name='password_reset_complete'),
    # url('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
handler404= 'Admin.views.handler404'

Student/urls.py
from unicodedata import name
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from Student import views
app_name = "Student"

urlpatterns = [
    path('SProfile', views.Profile , name='SProfile'  ),
    path('SProfile', views.Profile , name='SProfile'  ),
    path('Lecturevideo', views.Lecturevideo , name='Lecturevideo'  ),
    path('payment', views.payment , name='payment'  ),
    path('paymenthandler/', views.paymenthandler , name='paymenthandler'  ),
    path('paymentstatus', views.paymentstatus , name='paymentstatus'  ),
    path('invoice2/<int:id>/', views.invoice2 , name='invoice2'  ),
    
    # path('Student_Admission', views.Student_Admission , name='Student_Admission'  ),
    # path('Home', views.Student_Admission , name="Home" ),
    # path('Recheck', views.Student_Admission_recheck , name='Recheck' ),
    
    # path('Manage-Lecture',Lectureviews.Lecture_manage ,name='Manage-Lecture'),
    # path('Lecture_edit/<int:id>/',Lectureviews.Lecture_edit ,name='Lecture_edit'),

    # revenue
    # path('Revenue',revenueviews.revenue,name='Revenue'),
    # path('Todays_Revenue',revenueviews.Todays_Revenue,name='Todays_Revenue'),
    # path('totalrevenue',revenueviews.totalrevenue,name='totalrevenue'),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/urls.py
from django.contrib import admin
from django.urls import path

from Student import views
from accounts import views
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.contrib.auth import views as auth_views
from .forms import MyPasswordResetForm,MySetPasswordForm
# from Student import views
from accounts import views

app_name = "accounts"

urlpatterns = [
    # path('', views.Student_Admission  ) ,
    # path('accounts/', views.signup  ) ,
    # path('signup/' ,views.signup, name='signup'),
    path('login/' ,views.login, name='login'),
    path('logout/' ,views.logout, name='logout'),
    path('password-reset1/' ,views.password_reset_request, name='password-reset1'),

    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html',form_class=MyPasswordResetForm),name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html',form_class=MySetPasswordForm),name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),name='password_reset_complete'),
    
]

templates/Base/studentbase.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Titan Aviation</title>
    <!-- App favicon -->
    <link rel="shortcut icon" href="/static/Base/assets/images/fav-i.jpg" />

    <!-- App css -->
    <link
      href="/static/Base/assets/css/icons.min.css"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="/static/Base/assets/css/app.min.css"
      rel="stylesheet"
      type="text/css"
      id="app-style"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/plyr/3.6.12/plyr.min.css"
    />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/plyr/3.6.12/plyr.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
    <!-- data table -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.21/css/jquery.dataTables.min.css"
    />
    <!-- data table -->
  </head>

  <body
    class="loading"
    data-layout-color="light"
    data-leftbar-theme="dark"
    data-layout-mode="fluid"
    data-rightbar-onstart="true"
  >
    {% load sweetify %} {% sweetify %}

    <!-- Begin page -->
    <div class="wrapper">
      <!-- ========== Left Sidebar Start ========== -->
      <div class="leftside-menu">
        <div class="h-100" id="leftside-menu-container" data-simplebar>
          <!--- Sidemenu -->
          <ul class="side-nav">
            <li class="side-nav-title side-nav-item">Titan Aviation</li>

            <li class="side-nav-item">
              <a
                data-bs-toggle="collapse"
                href="#sidebarDashboards"
                aria-expanded="false"
                aria-controls="sidebarDashboards"
                class="side-nav-link"
              >
                <i class="uil-home-alt"></i>

                <span> Student Item </span>
              </a>
              <div class="collapse" id="sidebarDashboards">
                <ul class="side-nav-second-level">
                  <li>
                    <a href="{% url 'Admin:AHome' %}">Home</a>
                  </li>
                  <li>
                    <a href="{% url 'Admin:AdminProfile' %}">Student Profile</a>
                  </li>

                  <li>
                    <a href="/Lecturevideo">Lecture Video</a>
                  </li>
                  <li>
                    <a href="{% url 'Student:paymentstatus' %}"
                      >Payment Status</a
                    >
                  </li>
                </ul>
              </div>
            </li>
          </ul>

          <!-- End Sidebar -->

          <div class="clearfix"></div>
        </div>
        <!-- Sidebar -left -->
      </div>
      <!-- Left Sidebar End -->

      <!-- ============================================================== -->
      <!-- Start Page Content here -->
      <!-- ============================================================== -->

      <div class="content-page">
        <div class="content">
          <!-- Topbar Start -->
          <div class="navbar-custom">
            <ul class="list-unstyled topbar-menu float-end mb-0">
              <li class="dropdown notification-list d-lg-none">
                <a
                  class="nav-link dropdown-toggle arrow-none"
                  data-bs-toggle="dropdown"
                  href="#"
                  role="button"
                  aria-haspopup="false"
                  aria-expanded="false"
                >
                  <i class="dripicons-search noti-icon"></i>
                </a>
                <div
                  class="dropdown-menu dropdown-menu-animated dropdown-lg p-0"
                >
                  <form class="p-3">
                    <input
                      type="text"
                      class="form-control"
                      placeholder="Search ..."
                      aria-label="Recipient's username"
                    />
                  </form>
                </div>
              </li>

              <li class="dropdown notification-list">
                <a
                  class="nav-link dropdown-toggle nav-user arrow-none me-0 d-flex align-items-center"
                  data-bs-toggle="dropdown"
                  href="#"
                  role="button"
                  aria-haspopup="false"
                  aria-expanded="false"
                >
                  <span class="account-user-avatar">
                    <img
                      src="/static/Base/assets/images/users/avatar-1.jpg"
                      alt="user-image"
                      class="rounded-circle"
                    />
                  </span>

                  <span>
                    <span class="account-user-name"
                      >{{request.user}} <i class="dripicons-gear"></i>
                    </span>
                  </span>
                </a>
                <div
                  class="dropdown-menu dropdown-menu-end dropdown-menu-animated topbar-dropdown-menu profile-dropdown"
                >
                  <!-- item-->
                  <div class="dropdown-header noti-title">
                    <h6 class="text-overflow m-0">Welcome !</h6>
                  </div>

                  <div class="dropdown-header noti-title">
                    <span>
                      <a href="{% url 'Student:payment' %}" class="text-success"
                        >Complete your fee</a
                      ></span
                    >
                  </div>

                  <!-- item-->
                  <a
                    href="javascript:void(0);"
                    class="dropdown-item notify-item"
                  >
                    <i class="mdi mdi-account-circle me-1"></i>
                    <span>My Account</span>
                  </a>

                  <!-- item-->
                  <a
                    href="javascript:void(0);"
                    class="dropdown-item notify-item"
                  >
                    <i class="mdi mdi-logout me-1"></i>

                    <span data-bs-toggle="modal" data-bs-target="#logout">
                      Log Out
                    </span>
                  </a>
                </div>
              </li>
            </ul>
            <button class="button-menu-mobile open-left">
              <i class="mdi mdi-menu"></i>
            </button>
          </div>
          <!-- end Topbar -->

          <!-- Start Content-->
          <div class="container-fluid">
            <!-- /.modal  log out-->
            <div
              id="logout"
              class="modal fade"
              tabindex="-1"
              role="dialog"
              aria-hidden="true"
            >
              <div class="modal-dialog modal-top">
                <div class="modal-content">
                  <div class="modal-header">
                    <h4 class="modal-title" id="topModalLabel">Logout</h4>
                    <button
                      type="button"
                      class="btn-close"
                      data-bs-dismiss="modal"
                      aria-hidden="true"
                    ></button>
                  </div>
                  <form method="POST" action="{% url 'accounts:logout' %}">
                    <div class="modal-body">
                      {% csrf_token %}
                      <p class="text-danger fw-bold">
                        Are you sure you want to logout?
                      </p>
                    </div>
                    <div class="modal-footer">
                      <a class="btn btn-info" data-bs-dismiss="modal">Close</a>
                      <button type="submit" class="btn btn-danger">
                        Submit
                      </button>
                    </div>
                  </form>
                </div>
                <!-- /.modal-content -->
              </div>
              <!-- /.modal-dialog -->
            </div>
            <!-- /.modal  log out-->
            <div class="row">
              <div class="col-12">{% block body %} {% endblock %}</div>
            </div>
          </div>
          <!-- container -->
        </div>
        <!-- content -->
      </div>

      <!-- ============================================================== -->
      <!-- End Page content -->
      <!-- ============================================================== -->
    </div>

    <!-- END wrapper -->
    <!-- bundle -->
    <script src="/static/Base/assets/js/vendor.min.js"></script>
    <script src="/static/Base/assets/js/app.min.js"></script>
    <!-- sweet alart -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>

    <script src="https://unpkg.com/boxicons@2.1.1/dist/boxicons.js"></script>
    <!-- sweet alart -->

    <!-- chart js cdn -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <!-- chart js cdn -->
    <!-- data table -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.21/js/jquery.dataTables.min.js"></script>

    <!-- data table -->
  </body>
</html>

templates/Base/teacherbase.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Titan Aviation</title>
    <!-- App favicon -->
    <link rel="shortcut icon" href="/static/Base/assets/images/fav-i.jpg" />

    <!-- App css -->
    <link
      href="/static/Base/assets/css/icons.min.css"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="/static/Base/assets/css/app.min.css"
      rel="stylesheet"
      type="text/css"
      id="app-style"
    />

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
    <!-- data table -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.21/css/jquery.dataTables.min.css"
    />

    <!-- data table -->
  </head>

  <body
    class="loading"
    data-layout-color="light"
    data-leftbar-theme="dark"
    data-layout-mode="fluid"
    data-rightbar-onstart="true"
  >
    {% load sweetify %} {% sweetify %}

    <!-- Begin page -->
    <div class="wrapper">
      <!-- ========== Left Sidebar Start ========== -->
      <div class="leftside-menu">
        <!-- LOGO -->
        <a href="index.html" class="logo text-center logo-light">
          <span class="logo-lg">
            <img src="/static/Base/assets/images/logo.png" alt="" height="16" />
          </span>
          <span class="logo-sm">
            <img
              src="/static/Base/assets/images/logo_sm.png"
              alt=""
              height="16"
            />
          </span>
        </a>

        <!-- LOGO -->
        <a href="index.html" class="logo text-center logo-dark">
          <span class="logo-lg">
            <img
              src="/static/Base/assets/images/logo-dark.png"
              alt=""
              height="16"
            />
          </span>
          <span class="logo-sm">
            <img
              src="/static/Base/assets/images/logo-dark.png"
              alt=""
              height="16"
            />
          </span>
        </a>

        <div class="h-100" id="leftside-menu-container" data-simplebar>
          <!--- Sidemenu -->
          <ul class="side-nav">
            <li class="side-nav-title side-nav-item">Titan Aviation</li>

            <li class="side-nav-item">
              <a
                data-bs-toggle="collapse"
                href="#sidebarDashboards"
                aria-expanded="false"
                aria-controls="sidebarDashboards"
                class="side-nav-link"
              >
                <i class="uil-home-alt"></i>
                <span class="badge bg-success float-end">4</span>
                <span> Teacher Item </span>
              </a>
              <div class="collapse" id="sidebarDashboards">
                <ul class="side-nav-second-level">
                  <li>
                    <a href="{% url 'Admin:AHome' %}">Home</a>
                  </li>
                  <li>
                    <a href="{% url 'Admin:AdminProfile' %}">Teacher Profile</a>
                  </li>

                  <li>
                    <a href="/TLectureboard">Lecture Item</a>
                  </li>
                  <li>
                    <a href="/paymentlist">Payment List</a>
                  </li>
                  <li>
                    <a href="/duelist">Due List</a>
                  </li>
                  <li>
                    <a href="/TCourseboard">Course</a>
                  </li>
                  <li>
                    <a href="/Studentboard">Student item</a>
                  </li>
                  <li>
                    <a href="/TAddstudent">Add student</a>
                  </li>
                </ul>
              </div>
            </li>
          </ul>

          <!-- End Sidebar -->

          <div class="clearfix"></div>
        </div>
        <!-- Sidebar -left -->
      </div>
      <!-- Left Sidebar End -->

      <!-- ============================================================== -->
      <!-- Start Page Content here -->
      <!-- ============================================================== -->

      <div class="content-page">
        <div class="content">
          <!-- Topbar Start -->
          <div class="navbar-custom">
            <ul class="list-unstyled topbar-menu float-end mb-0">
              <li class="dropdown notification-list d-lg-none">
                <a
                  class="nav-link dropdown-toggle arrow-none"
                  data-bs-toggle="dropdown"
                  href="#"
                  role="button"
                  aria-haspopup="false"
                  aria-expanded="false"
                >
                  <i class="dripicons-search noti-icon"></i>
                </a>
                <div
                  class="dropdown-menu dropdown-menu-animated dropdown-lg p-0"
                >
                  <form class="p-3">
                    <input
                      type="text"
                      class="form-control"
                      placeholder="Search ..."
                      aria-label="Recipient's username"
                    />
                  </form>
                </div>
              </li>

              <li class="dropdown notification-list">
                <a
                  class="nav-link dropdown-toggle nav-user arrow-none me-0 d-flex align-items-center"
                  data-bs-toggle="dropdown"
                  href="#"
                  role="button"
                  aria-haspopup="false"
                  aria-expanded="false"
                >
                  <span class="account-user-avatar">
                    <img
                      src="/static/Base/assets/images/users/avatar-1.jpg"
                      alt="user-image"
                      class="rounded-circle"
                    />
                  </span>
                  <span>
                    <span class="account-user-name"
                      >{{request.user}} <i class="dripicons-gear"></i
                    ></span>
                  </span>
                </a>
                <div
                  class="dropdown-menu dropdown-menu-end dropdown-menu-animated topbar-dropdown-menu profile-dropdown"
                >
                  <!-- item-->
                  <div class="dropdown-header noti-title">
                    <h6 class="text-overflow m-0">Welcome !</h6>
                  </div>

                  <!-- item-->
                  <a
                    href="javascript:void(0);"
                    class="dropdown-item notify-item"
                  >
                    <i class="mdi mdi-account-circle me-1"></i>
                    <span>My Account</span>
                  </a>

                  <!-- item-->
                  <a
                    href="javascript:void(0);"
                    class="dropdown-item notify-item"
                  >
                    <i class="mdi mdi-logout me-1"></i>

                    <span data-bs-toggle="modal" data-bs-target="#logout">
                      Log Out
                    </span>
                  </a>
                </div>
              </li>
            </ul>
            <button class="button-menu-mobile open-left">
              <i class="mdi mdi-menu"></i>
            </button>
          </div>
          <!-- end Topbar -->

          <!-- Start Content-->
          <div class="container-fluid">
            <!-- /.modal  log out-->
            <div
              id="logout"
              class="modal fade"
              tabindex="-1"
              role="dialog"
              aria-hidden="true"
            >
              <div class="modal-dialog modal-top">
                <div class="modal-content">
                  <div class="modal-header">
                    <h4 class="modal-title" id="topModalLabel">Logout</h4>
                    <button
                      type="button"
                      class="btn-close"
                      data-bs-dismiss="modal"
                      aria-hidden="true"
                    ></button>
                  </div>
                  <form method="POST" action="{% url 'accounts:logout' %}">
                    <div class="modal-body">
                      {% csrf_token %}
                      <p class="text-danger fw-bold">
                        Are you sure you want to logout?
                      </p>
                    </div>
                    <div class="modal-footer">
                      <a class="btn btn-info" data-bs-dismiss="modal">Close</a>
                      <button type="submit" class="btn btn-danger">
                        Submit
                      </button>
                    </div>
                  </form>
                </div>
                <!-- /.modal-content -->
              </div>
              <!-- /.modal-dialog -->
            </div>
            <!-- /.modal  log out-->
            <div class="row">
              <div class="col-12">
                <script
                  src="https://code.jquery.com/jquery-3.6.0.min.js"
                  integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
                  crossorigin="anonymous"
                ></script>
                {% block body %} {% endblock %}
              </div>
            </div>
          </div>
          <!-- container -->
        </div>
        <!-- content -->
      </div>

      <!-- ============================================================== -->
      <!-- End Page content -->
      <!-- ============================================================== -->
    </div>

    <!-- END wrapper -->

    <!-- bundle -->
    <script src="/static/Base/assets/js/vendor.min.js"></script>
    <script src="/static/Base/assets/js/app.min.js"></script>
    <!-- sweet alart -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>

    <script src="https://unpkg.com/boxicons@2.1.1/dist/boxicons.js"></script>
    <!-- sweet alart -->

    <!-- chart js cdn -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <!-- chart js cdn -->
    <!-- data table -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.21/js/jquery.dataTables.min.js"></script>

    <!-- data table -->
  </body>
</html>