Admin/urls.py
from unicodedata import name
from django import views
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from Admin import Lectureview, views ,Revanueview
from Admin.views import Home
#from django.conf.urls import url
app_name = "Admin"

urlpatterns = [
    path('', views.Home , name='Home'),
    path('AHome', views.Home , name='AHome'),
    # lecture
    path('Lectureboard', Lectureview.Lectureboard , name='Lectureboard'),
    path('Addlecture', Lectureview.Lectures , name="Addlecture"),
    path('Lecture_edit/<int:id>/', Lectureview.Lecture_edit , name='Lecture_edit'),
    path('Leature_delete/<int:id>/', Lectureview.Leature_delete , name='Leature_delete'),
    # lecture
    
    # course
    path('Courseboard', views.Courseboard , name='Courseboard'),
    path('Addcourse', views.Addcourse , name='Addcourse'),
    path('Course_edit/<int:id>/', views.Course_edit , name='Course_edit'),
    path('Course_delete/<int:id>/', views.Course_delete , name='Course_delete'),
    # course
    
    # add teacher
    path('Addteacher', views.Addteacher , name='Addteacher'),
    path('Addteacherdetail', views.Addteacherdetail , name='Addteacherdetail'),
    # add teacher
    
    path('AdminProfile', views.Profile , name='AdminProfile'),
    path('Revenue', Revanueview.Revenue , name="Revenue"),
    path('paymentlist', Revanueview.paymentlist , name="paymentlist"),
    path('duelist', Revanueview.duelist , name="duelist"),

    # add student
    
    path('Studentboard', views.Studentboard , name="Studentboard"),
    path('Student_edit/<int:id>/', views.Student_edit , name="Student_edit"),
    path('Student_delete/<int:id>/', views.Student_delete , name="Student_delete"),
    path('Addstudent', views.Addstudent , name="Addstudent"),
    path('ADDstudent', views.ADDstudent , name="ADDstudent"),
    
    # path('Recheck', views.Student_Admission_recheck , name='Recheck' ),
    # add student
    
    # revenue
    # path('Revenue',revenueviews.revenue,name='Revenue'),
    # path('Todays_Revenue',revenueviews.Todays_Revenue,name='Todays_Revenue'),
    # path('totalrevenue',revenueviews.totalrevenue,name='totalrevenue'),
    
   

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

BRD/urls.py
from django.contrib import admin
from django.urls import path,include
#from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
# import notifications.urls

from django.conf.urls import include
from django.views.generic.base import TemplateView
from django.contrib.auth import views as auth_views
from Admin import views
admin.site.site_header = 'Student Admission'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include( 'Home.urls')),
    path('',include( 'Student.urls')),
    path('',include( 'Teacher.urls')),
    path('',include( 'Admin.urls')),
    path('accounts/',include ('accounts.urls')),
    path('robots.txt',TemplateView.as_view(template_name="Base/robots.txt", content_type="text/plain")),
    path(r'^$',views.handler404, name='handler404'),
    #url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    # url('', include('social_django.urls', namespace='social')),
    #  path('forest', include('django_forest.urls')),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),name='password_reset_complete'),
    # url('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
handler404= 'Admin.views.handler404'

Home/urls.py
from unicodedata import name
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf import settings
from django.conf.urls.static import static
from  Home import views
from django.views.static import serve


app_name = "Home"

urlpatterns = [
    # path('Student_Admission', views.Student_Admission , name='Student_Admission'  ),
    path('', views.Home  ),
    path('Base', views.Home , name="Base" ),
    path('Home', views.Home , name="Home" ),
    path('email_Data', views.email_Data , name="email_Data" ),
    path('Online-Admission', views.Addstudent , name="Online-Admission" ),
    path('About-Us', views.About , name="About-Us" ),
    path('ContactUs', views.ContactUs , name="ContactUs" ),
    path('Term-and-condition', views.TAC , name="Term-and-condition" ),
    path('Refund-&-Cancellation', views.TAC2 , name="Refund-&-Cancellation" ),
    path('allcourse/', views.allcourse.as_view(), name='allcourse'),
    path('privacypolicy', views.privacypol , name="privacypolicy" ),	
    path('coursedetailview/<slug>', views.coursedetailview.as_view(), name='coursedetailview'),
    path('blogdetailview/<slug>', views.blogdetailview.as_view(), name='blogdetailview'),
    path('eventdetailview/<slug>', views.eventdetailview.as_view(), name='eventdetailview'),
    path('blogpage/',views.blogpage.as_view(),name='blogpage'),



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, }),


]

Student/urls.py
from unicodedata import name
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from Student import views
app_name = "Student"

urlpatterns = [
    path('SProfile', views.Profile , name='SProfile'  ),
    path('SProfile', views.Profile , name='SProfile'  ),
    path('Lecturevideo', views.Lecturevideo , name='Lecturevideo'  ),
    path('payment', views.payment , name='payment'  ),
    path('paymenthandler/', views.paymenthandler , name='paymenthandler'  ),
    path('paymentstatus', views.paymentstatus , name='paymentstatus'  ),
    path('invoice2/<int:id>/', views.invoice2 , name='invoice2'  ),
    
    # path('Student_Admission', views.Student_Admission , name='Student_Admission'  ),
    # path('Home', views.Student_Admission , name="Home" ),
    # path('Recheck', views.Student_Admission_recheck , name='Recheck' ),
    
    # path('Manage-Lecture',Lectureviews.Lecture_manage ,name='Manage-Lecture'),
    # path('Lecture_edit/<int:id>/',Lectureviews.Lecture_edit ,name='Lecture_edit'),

    # revenue
    # path('Revenue',revenueviews.revenue,name='Revenue'),
    # path('Todays_Revenue',revenueviews.Todays_Revenue,name='Todays_Revenue'),
    # path('totalrevenue',revenueviews.totalrevenue,name='totalrevenue'),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Home/models.py
from email import message
from django.db import models
from ckeditor.fields import RichTextField
from autoslug import AutoSlugField


# Create your models here.
class query_form(models.Model):
    form_name = models.CharField(max_length=100,null=True)
    form_email = models.CharField(max_length=100,null=True)
    form_subject = models.CharField(max_length=100,null=True)
    form_message = models.CharField(max_length=1000,null=True)
    created = models.DateTimeField(auto_now_add=True,null=True)


    def __str__(self):
        return self.form_subject


class slider(models.Model):
    slider_name = models.CharField(null=True , max_length = 50 )
    slider_img = models.ImageField(upload_to='static/slider', null=True ,max_length = 100)
    Details = RichTextField(blank=True , null=True)
    
    def __str__(self):
        return self.slider_name
    
    
class q_form(models.Model):
    name = models.CharField(max_length=50,null=True)
    email = models.EmailField( max_length=254 , null=True) 
    phone = models.CharField(max_length=15 , null=True)
    message = models.CharField( max_length=500, null=True)
    subject = models.CharField(max_length=100,null=True)
       
       
class email_data(models.Model):
    email = models.EmailField( max_length=254 , null=True)       
    def __str__(self):
        return self.email


class blog(models.Model):
    blog_title = models.CharField(max_length=300, null=True)
    blog_img = models.ImageField(blank=True, upload_to='media')
    blog_desp = RichTextField()
    blog_date = models.DateField(auto_now_add=False)
    blog_author = models.CharField(max_length=30,null=True)
    blog_slug = AutoSlugField(populate_from='blog_title',unique=True ,default=None, blank=False, null=True)

class Course(models.Model):
    course_img = models.ImageField(upload_to='media', blank=False)
    course_bann = models.ImageField(upload_to='media', blank=False,null=True)
    course_price = models.CharField(max_length=6, null=True)
    course_title = models.CharField(max_length=50,null=True, blank=False)
    course_descp = RichTextField(blank=False, null=False)
    course_stu = models.CharField(max_length=5,null=True)
    course_lessons = models.CharField(max_length=4, null=True)
    course_slug = AutoSlugField(populate_from='course_title',unique=True ,default=None, blank=False, null=True)

class StuReview(models.Model):
    stu_name = models.CharField(max_length=40, null=True)
    stu_descp = models.CharField(max_length=500,null=True)

class Event(models.Model):
    event_title = models.CharField(max_length=200,null=True, blank=False)
    event_img = models.ImageField(upload_to='media', blank=False)
    event_descp = RichTextField(blank=False, null=False)
    event_date = models.DateField(auto_now_add=False)
    event_time = models.TimeField(auto_now_add=False)
    event_location = models.CharField(max_length=30,null=True)
    event_slug = AutoSlugField(populate_from='event_title',unique=True ,default=None, blank=False, null=True)

Student/forms.py
from xml.dom.minidom import Attr
from django import forms
from Student.models import Student_detail
from django.forms import ModelForm, Select, Textarea, TextInput, NumberInput, DateField
from datetime import datetime

class Student_detailForm(forms.ModelForm):
    class Meta:
        cls_sty = 'form-control  '
        model = Student_detail
        fields = ['Name', 'Email',  'Number', 'DOB', 'Aadhaar', 'Gender', 'Education', 'doc_10th', 'doc_12th', 'doc_Graduate',
                  'doc_postgraduate', 'Course_name', 'Address',  'State',  'District', 'Pincode']

        # fields = '__all__'
        label = {
            'Gender': 'Gender',
            'Date': 'Date'
        }
        widgets = {
            'Name': forms.TextInput(attrs={'class': cls_sty, 'type': 'text','placeholder': 'Name','pattern':"[a-zA-Z'-'\s]*"}),
            'Email': forms.TextInput(attrs={'class': 'form-control', 'type': 'email', 'placeholder': 'Email'}),
            'Number': forms.TextInput(attrs={'class': cls_sty, 'type': 'number','placeholder':'Mobile No.','onKeyPress':"if(this.value.length==10) return false;" }),
            #  'Number2' : forms.TextInput(attrs={'class': cls_sty ,'type':'phone' ,'placeholder':'Alternate No.'}),
            'Gender': Select(attrs={'class': 'form-control', 'type': 'choice'}),
            'DOB': forms.DateInput(attrs={'class': cls_sty,
                                          'type': 'date',
                                          'max' : datetime.now().date()
                                          }),
            'Education': Select(attrs={'class': 'form-control ', 'type': 'choice'}),

            'Aadhaar': forms.TextInput(attrs={'class': cls_sty, 'type': 'number','placeholder': 'Aadhaar No.','onKeyPress':"if(this.value.length==12) return false;"}),
            'Course_name': Select(attrs={'class': 'form-control', 'type': 'choice'}),
            
            'doc_10th': forms.FileInput(attrs={'class': cls_sty, 'type': 'file'}),
            'doc_12th': forms.FileInput(attrs={'class': cls_sty, 'type': 'file'}),
            'doc_Graduate': forms.FileInput(attrs={'class': cls_sty, 'type': 'file'}),
            'doc_postgraduate': forms.FileInput(attrs={'class': cls_sty, 'type': 'file'}),
	        'Address': forms.TextInput(attrs={'class': cls_sty, 'placeholder': 'Address'}),
            'State': Select(attrs={'class': 'form-control','type': 'choice' }),
            'City': forms.TextInput(attrs={'class': cls_sty}),
            'House': forms.TextInput(attrs={'class': cls_sty}),
            'Post_office': forms.TextInput(attrs={'class': cls_sty}),
            'Tehsil': forms.TextInput(attrs={'class': cls_sty}),
            'District': forms.TextInput(attrs={'class': cls_sty}),
            'Pincode': forms.TextInput(attrs={'class': cls_sty,'type': 'number','placeholder': 'Pin Code','onKeyPress':"if(this.value.length==6) return false;"}),
        }
        

Home/views.py
from django.shortcuts import redirect, render,HttpResponseRedirect
from django.urls import reverse
from Student.forms import Student_detailForm
from Home.models import *
import sweetify
from django.views import View
from django.shortcuts import HttpResponse
from django.contrib import messages
# Create your views here.


def Home(request):
    course = Course.objects.all().order_by('id').reverse()[0:3]
    stur = StuReview.objects.all().order_by('id').reverse()
    eve = Event.objects.all().order_by('id').reverse()
    return render(request, 'Home/index.html',{'course':course,'stur':stur,'eve':eve})


def email_Data(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        emaildata = email_data.objects.create(email=email)
        emaildata.save()
        messages.info(request,"Successfully Submitted")
        # sweetify.success(request, 'Hey', text= 'You have successfully Subscribed', persistent='Done')
        return redirect('Home:Home')
        

def Addstudent(request):
    form = Student_detailForm()
    context = {
        'form':form
    }
    return render(request, 'Home/Addstudent.html' , context)
def About(request):
    return render(request, 'Home/about.html')

def ContactUs(request):
    if request.method == "POST":
        name = request.POST.get('name')
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        subject = request.POST.get('subject')
        qform = q_form.objects.create(name = name , email=email , phone = phone , message = message,subject=subject)
        qform.save()
        messages.info(request,"Successfully Submitted")
        # sweetify.success(request, 'Hey', text= 'You have successfully filled the form', persistent='Done')
        return HttpResponseRedirect(reverse('Home:ContactUs'))
    return render(request, 'Home/contactUs.html')

class blogpage(View):
    def get(self,request):
        bl = blog.objects.all()
        return render(request, 'Home/blog.html', {'bl':bl })

class blogdetailview(View):
    def get(self,request,slug):
        Blog = blog.objects.get(blog_slug=slug)
        Blog_object=blog.objects.get(blog_slug=slug)
        Blog_object.save()

        return render(request, 'Home/blogdetail.html',{'Blog':Blog})

class eventdetailview(View):
    def get(self,request,slug):
        event = Event.objects.get(event_slug=slug)
        event_object=Event.objects.get(event_slug=slug)
        event_object.save()

        return render(request, 'Home/eventdetail.html',{'event':event})

def TAC(request):
    return render(request, 'Home/titan.html')
def TAC2(request):
    return render(request, 'Home/TAC.html')

class allcourse(View):
    def get(self,request):
        course = Course.objects.all().order_by('id').reverse()[0:6]
        return render(request, 'Home/allcourse.html', {'course':course})

class coursedetailview(View):
    def get(self,request,slug):
        course = Course.objects.get(course_slug=slug)
        course_object=Course.objects.get(course_slug=slug)
        course_object.save()

        return render(request, 'Home/coursedetail.html',{'course':course})

def privacypol(request):
    return render(request, 'Home/privacypolicy.html')

templates/Students/Home.html
{% extends 'Base/studentbase.html' %}
{% block body %}
<div class="row">
    <div class="col-xxl-3 col-md-4 col-sm-6">
        <a href="{% url 'Student:Lecturevideo' %}">
            <div class="card widget-flat bg-danger text-white">
                <div class="card-body">
                    <div class="float-end">
                        <i class="mdi mdi-currency-rupee widget-icon bg-white text-success"></i>
                    </div>
                    <h6 class="text-uppercase mt-0" title="Customers">Lecture</h6>
                    <h3 class="mt-3 mb-3">{{lecture}}</h3>
                </div>
            </div>
        </a>
    </div>
    <div class="col-xxl-3 col-md-4 col-sm-6">
        <a href="{% url 'Student:SProfile' %}">
            <div class="card widget-flat bg-success text-white">
                <div class="card-body">
                    <div class="float-end">
                        <i class="mdi mdi-account-multiple widget-icon bg-white text-success"></i>
                    </div>
                    <h6 class="text-uppercase mt-0" title="Customers">Profile</h6>
                    <h3 class="mt-3 mb-3"></h3>
                </div>
            </div>
        </a>
    </div>
    <div class="col-xxl-3 col-md-4 col-sm-6">
        <a href="{% url 'Student:payment' %}">
            <div class="card widget-flat bg-primary text-white">
                <div class="card-body">
                    <div class="float-end">
                        <i class="mdi mdi-book-education widget-icon bg-white text-success"></i>
                    </div>
                    <h6 class="text-uppercase mt-0" title="Customers">Payment</h6>
                    <h3 class="mt-3 mb-3"></h3>
                </div>
            </div>
        </a>
    </div>
    
    
</div>
{% endblock  %}

templates/Students/Lecturevideo.html
{% extends 'Base/studentbase.html'%}

{% block body %}
<div class="row mt-3">
  {% if Test.Payment %} {% for item in lecture %}
  <div class="col-md-6 mb-3">
    {% if item.youtube_url is not None %}
    <div class="card">
      <div class="card-header text-center bg-info">
        <p class="mb-0 text-light">Video No. {{item.lecture_num}}</p>
      </div>
      <div class="card m-4">
        <div class="plyr__video-embed" id="player{{item.id}}">
          <iframe
            src="{{item.youtube_url}}"
            frameborder="0"
            allow="autoplay; fullscreen; picture-in-picture"
            allowfullscreen
          ></iframe>
        </div>
      </div>
      <div class="card-footer">
        <p class="fw-bold mb-0">Title: {{item.title}}</p>
      </div>
    </div>
    {% else %}
    <div class="card">
      <div class="card-header bg-info">
        <p class="mb-0 text-center text-light">
          Video No. {{item.lecture_num}}
        </p>
      </div>
      <div class="card mt-3">
        <div class="plyr__video-embed" id="player{{item.id}}">
          <iframe
            class="ifm"
            src="{{item.vimeo_url}}?h=e56d64a085&title=0&byline=0&portrait=0"
            frameborder="0"
            allow="autoplay; fullscreen; picture-in-picture"
            allowfullscreen
          ></iframe>  
        </div>
      </div>
      <div class="card-footer">
        <p class="fw-bold mb-0">Title: {{item.title}}</p>
      </div>
    </div>
    {% endif %}
  </div>
  <script>
    const player = new Plyr("#player{{item.id}}");
  </script>
  {% endfor %} {% else %}
</div>
<h3 class="text-center mb-0 mt-5">Please Complete your Payment</h3>
<div class="d-flex justify-content-center"><img src="/static/Base/assets/images/bill.png" alt="bill" class="w-25"></div>
<!-- new -->
<div class="text-center">
  <a href="{% url 'Student:payment' %}" class="btn btn-primary px-4">PAY</a>
</div>
{% endif %} {% endblock %}

templates/Students/Profile.html
{% extends 'Base/studentbase.html'%} {% block body %}
<div class="row">
  <div class="col-12 mt-3">
    <div class="card text-center">
      <div class="card-body">
        <img
          src="/static/Home/assets/images/nlogo/fav-i.jpg"
          class="rounded-circle avatar-lg img-thumbnail"
          alt="profile-image"
        />
        <h4 class="mb-0 mt-2">{{ request.user }}</h4>
        <h4 class="mb-0 mt-2">{{ request.user.get_full_name }}</h4>
        <hr />
        <div class="row">
          <div class="col-md-6">
            <div class="text-start mt-3">
              <h4 class="font-13 text-uppercase">About Me :</h4>
              <p class="text-muted font-13 mb-2">{{data.about}}</p>
              <p class="text-muted mb-2 font-13">
                <strong>Full Name :</strong>
                <span class="ms-2">{{ request.user.get_full_name }}</span>
              </p>
              <p class="text-muted mb-2 font-13">
                <strong>Mobile :</strong
                ><span class="ms-2">{{data.phone}}</span>
              </p>
              <p class="text-muted mb-2 font-13">
                <strong>Email :</strong>
                <span class="ms-2">{{ request.user.email }}</span>
              </p>
            </div>
            <p class="text-start">
              <a
                class="btn btn-primary"
                data-bs-toggle="collapse"
                href="#collapseExample"
                aria-expanded="false"
                aria-controls="collapseExample"
              >
                Edit Details
              </a>
            </p>
          </div>

          <div class="col-md-6">
            <div class="text-start mt-3">
              <h4 class="font-13 text-uppercase">Course :</h4>
              <p class="text-muted font-13 mb-2">{{data2.Course_name}}</p>
              <!-- <p class="text-muted mb-2 font-13">
               <strong>Paid amount :</strong>
                <span class="ms-2">{{ data2.paid_amount }}</span>
              </p>
-->
              <p class="text-muted mb-2 font-13">
                <strong>Admission_no :</strong
                ><span class="ms-2">{{data2.Admission_no}}</span>
              </p>
              <p class="text-muted mb-2 font-13">
                <strong>Enrollment_date :</strong>
                <span class="ms-2">{{data2.Enrollment_date }}</span>
              </p>
              <a
                href="{% url 'Student:payment' %}"
                class="btn btn-primary"
                id="pay-btn"
                >Complete your Payment</a
              >
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <div class="collapse" id="collapseExample">
          <div class="card">
            <div class="card-header bg-primary">
              <h4 class="mb-0 text-light text-center">Edit Details</h4>
            </div>
            <div class="card-body">
              <form action="{% url 'Admin:Addteacherdetail'  %}" method="post">
                {% csrf_token %} {% for fm in form %}
                <div class="col-md-12 mb-2">
                  <p class="text-start mb-1">{{fm.label_tag}}</p>
                  {{ fm }} {{ fm.errors }}
                </div>
                {% endfor %}
                <div class="text-start">
                  <button class="btn btn-primary" type="submit">Update</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  {% endblock %}
</div>

templates/Students/invoice.html
{% extends 'Base/studentbase.html' %}
{% block body %}
  

        <div class="container mt-5">
            <div class="row justify-content-center">
                <img src="static\Home\images\logo-egale.png" alt="" class="w-25" />
            </div>
            <h2 class="text-success text-center fw-bold my-3">Thank you for your payment</h2>

            <div class="table-responsive">
                <table class="table mb-4 w-75 mx-auto">
                    <tr>
                        <th>Name</th>
                        <td>{{context.Name}}</td>
                    </tr>
                    <tr>
                        <th>Email</th>
                        <td>{{context.Email}}</td>
                    </tr>
                    <tr>
                        <th>Mobile No</th>
                        <td>{{context.Number}}</td>
                    </tr>
                    <tr>
                        <th>Date Of Birth</th>
                        <td>{{context.DOB}}</td>
                    </tr>
                    <tr>
                        <th>Gender</th>
                        <td>{{context.Gender}}</td>
                    </tr>
                    <tr>
                        <th>Course Name</th>
                        <td>{{context.Course_name}}</td>
                    </tr>
                    <tr>
                        <th>Admission No</th>
                        <td>{{context.Admission_no}}</td>
                    </tr>
                    <tr>
                        <th>Date </th>
                        <td>{{datenow}}</td>
                    </tr>
                    <tr>
                        <th>Transaction ID</th>
                        <td>{{data}}</td>
                    </tr>
                    
                    <tr>
                        <th>Payment Status</th>
                        <td>Success</td>
                    </tr>
                    <tr>
                        <th>State</th>
                        <td>{{context.State}}</td>
                    </tr>
                    <tr>
                        <th>House No / Gali No</th>
                        <td>152</td>
                    </tr>
                    <tr>
                        <th>Village / Town / City</th>
                        <td>{{context.City}}</td>
                    </tr>
                    <tr>
                        <th>Ward No / Post Office</th>
                        <td>{{context.Post_office}}</td>
                    </tr>
                    <tr>
                        <th>Tahsil / Block</th>
                        <td>{{context.Block}}</td>
                    </tr>
                    <tr>
                        <th>District</th>
                        <td>{{context.District}}</td>
                    </tr>
                    <tr>
                        <th>Pincode</th>
                        <td>{{context.Pincode}}</td>
                    </tr>
                    
                </table>
            </div>
            <div class="text-center mb-5"><button class="btn btn-primary d-print-none" onclick="print()">Print/Download as PDF</button></div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
{% endblock body %}
    

templates/Students/payment.html
{% extends 'Base/studentbase.html' %}
{% block body %}

	<div class="container mt-5">
        <div class="row">
            <div class="col-md-12">
                <div class="card shadow-lg">
                <div class="card-header py-3">
                        <h3 class="mb-0 text-center">Your Lecture will be available after your installment</h3>
                    </div>
                <div class="card-body p-5">
                   <div class="table-responsive">
                       <table class="table table-bordered">
                           <thead>
                               <tr>
                                   <th>Name</th>
                                   <th>Email</th>
                                   <th>Course</th>
                                   <th>Course Price</th>
                                   <th>Due</th>
                               </tr>
                           </thead>
                           <tbody>
                               <tr>
                                   <td>{{item.Name}}</td>
                                   <td>{{item.Email}}</td>
                                   <td>{{item.Course_name}}</td>
                                   <td>{{item.Course_name.Price}} INR</td>
                                   <td class='fw-bold text-danger'> {{Due}}</td>
                               </tr>
                           </tbody>
                       </table>
                   </div>
                     <button class="btn btn-primary" id="pay-btn">PROCEED</button>
               
                </div>
                </div>
            </div>
        </div>
    </div>


<!-- Razorpay's Javascript code. -->
<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
<script>
	var options = {
	
	// Enter the Key ID generated from the Dashboard
	key: "{{ razorpay_merchant_key }}",
	
	// Amount is in currency subunits.
	// Default currency is INR. Hence,
	// 50000 refers to 50000 paise
	amount: "{{ razorpay_amount }}",
	currency: "{{ currency }}",
	
	// Your/store name.
	name: "BRD Institute",
    image: "static/Home/images/favicone.png",
	// Pass the `id` obtained in the response of Step 1
	order_id: "{{ razorpay_order_id }}",
	callback_url: "{{ callback_url }}",
    'prefill': {
        "name": "{{item.Name}}",
        "email": "{{item.Email}}",
        "contact": "{{item.Number}}",
    },
	};
	
	// initialise razorpay with the options.
	var rzp1 = new Razorpay(options);
	
	// add event listener to the payment button.
	document.getElementById("pay-btn").onclick = function (e) {
	rzp1.open();
	e.preventDefault();
	};
</script>
</html>


{% endblock %}

templates/Students/paymentstatus.html
{% extends 'Base/studentbase.html' %}

{% block body %}

<div class="container-fluid mt-5">
    <div class="row">
        <div class="col-md-12">
            <div class="card shadow-lg">
            <div class="card-header py-3">
                    <h3 class="mb-0 text-center">Your Lecture will be available after your installment</h3>
                </div>
            <div class="card-body p-1">
               <div class="table-responsive">
                   <table class="table table-bordered">
                       <thead>
                           <tr>
                               <th>Name</th>
                               <th>Email</th>
                               <th>Date</th>
                               <th>Amount</th>
                               <th>Payment ID</th>
                               <th>Download Invoice</th>
                           </tr>
                       </thead>
                       <tbody>
                           {% for item in data %}
                           <tr>
                               <td>{{item.name}}</td>
                               <td>{{item.user}}</td>
                               <td>{{item.date2}}</td>
                               <td>{{item.amount}}</td>
                               <td>{{item.payment_id}}</td>
                               <td><a href="{% url 'Student:invoice2' item.id %}">Invoice</a></td>
                           </tr>
                           {% endfor %}
                       </tbody>
                   </table>
               </div>
                 <a href="{% url 'Student:payment' %}" class="btn btn-primary mt-3" id="pay-btn">Complete your Payment</a>
           
            </div>
            </div>
        </div>
    </div>
</div>


{% endblock body %}

templates/Students/paymentsuccess.html
<h1>i am new</h1>