Admin/urls.py
from unicodedata import name
from django import views
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from Admin import Lectureview, views ,Revanueview
from Admin.views import Home
#from django.conf.urls import url
app_name = "Admin"

urlpatterns = [
    path('', views.Home , name='Home'),
    path('AHome', views.Home , name='AHome'),
    # lecture
    path('Lectureboard', Lectureview.Lectureboard , name='Lectureboard'),
    path('Addlecture', Lectureview.Lectures , name="Addlecture"),
    path('Lecture_edit/<int:id>/', Lectureview.Lecture_edit , name='Lecture_edit'),
    path('Leature_delete/<int:id>/', Lectureview.Leature_delete , name='Leature_delete'),
    # lecture
    
    # course
    path('Courseboard', views.Courseboard , name='Courseboard'),
    path('Addcourse', views.Addcourse , name='Addcourse'),
    path('Course_edit/<int:id>/', views.Course_edit , name='Course_edit'),
    path('Course_delete/<int:id>/', views.Course_delete , name='Course_delete'),
    # course
    
    # add teacher
    path('Addteacher', views.Addteacher , name='Addteacher'),
    path('Addteacherdetail', views.Addteacherdetail , name='Addteacherdetail'),
    # add teacher
    
    path('AdminProfile', views.Profile , name='AdminProfile'),
    path('Revenue', Revanueview.Revenue , name="Revenue"),
    path('paymentlist', Revanueview.paymentlist , name="paymentlist"),
    path('duelist', Revanueview.duelist , name="duelist"),

    # add student
    
    path('Studentboard', views.Studentboard , name="Studentboard"),
    path('Student_edit/<int:id>/', views.Student_edit , name="Student_edit"),
    path('Student_delete/<int:id>/', views.Student_delete , name="Student_delete"),
    path('Addstudent', views.Addstudent , name="Addstudent"),
    path('ADDstudent', views.ADDstudent , name="ADDstudent"),
    
    # path('Recheck', views.Student_Admission_recheck , name='Recheck' ),
    # add student
    
    # revenue
    # path('Revenue',revenueviews.revenue,name='Revenue'),
    # path('Todays_Revenue',revenueviews.Todays_Revenue,name='Todays_Revenue'),
    # path('totalrevenue',revenueviews.totalrevenue,name='totalrevenue'),
    
   

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

BRD/urls.py
from django.contrib import admin
from django.urls import path,include
#from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
# import notifications.urls

from django.conf.urls import include
from django.views.generic.base import TemplateView
from django.contrib.auth import views as auth_views
from Admin import views
admin.site.site_header = 'Student Admission'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include( 'Home.urls')),
    path('',include( 'Student.urls')),
    path('',include( 'Teacher.urls')),
    path('',include( 'Admin.urls')),
    path('accounts/',include ('accounts.urls')),
    path('robots.txt',TemplateView.as_view(template_name="Base/robots.txt", content_type="text/plain")),
    path(r'^$',views.handler404, name='handler404'),
    #url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    # url('', include('social_django.urls', namespace='social')),
    #  path('forest', include('django_forest.urls')),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),name='password_reset_complete'),
    # url('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
handler404= 'Admin.views.handler404'

Home/urls.py
from unicodedata import name
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf import settings
from django.conf.urls.static import static
from  Home import views
from django.views.static import serve


app_name = "Home"

urlpatterns = [
    # path('Student_Admission', views.Student_Admission , name='Student_Admission'  ),
    path('', views.Home  ),
    path('Base', views.Home , name="Base" ),
    path('Home', views.Home , name="Home" ),
    path('email_Data', views.email_Data , name="email_Data" ),
    path('Online-Admission', views.Addstudent , name="Online-Admission" ),
    path('About-Us', views.About , name="About-Us" ),
    path('ContactUs', views.ContactUs , name="ContactUs" ),
    path('Term-and-condition', views.TAC , name="Term-and-condition" ),
    path('Refund-&-Cancellation', views.TAC2 , name="Refund-&-Cancellation" ),
    path('allcourse/', views.allcourse.as_view(), name='allcourse'),
    path('privacypolicy', views.privacypol , name="privacypolicy" ),	
    path('coursedetailview/<slug>', views.coursedetailview.as_view(), name='coursedetailview'),
    path('blogdetailview/<slug>', views.blogdetailview.as_view(), name='blogdetailview'),
    path('eventdetailview/<slug>', views.eventdetailview.as_view(), name='eventdetailview'),
    path('blogpage/',views.blogpage.as_view(),name='blogpage'),



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, }),


]

Teacher/urls.py
from unicodedata import name
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from Teacher import views 

app_name = "Teacher"

urlpatterns = [
    # path('Profile', views.Profile , name='Profile'  ),
    path('TAddstudent', views.Addstudent , name='TAddstudent'  ),
    # leature
    path('TLectureboard', views.Lectureboard , name='TLectureboard'  ),
    path('TCourseboard', views.Courseboard , name='TCourseboard'),
    # leature
    #course 
    path('TLecture_edit/<int:id>/', views.edit_lecture , name='TLecture_edit'),
    path('TCourse_edit/<int:id>/', views.Course_edit , name='TCourse_edit'),
    #course 
    
    
    

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Home/models.py
from email import message
from django.db import models
from ckeditor.fields import RichTextField
from autoslug import AutoSlugField


# Create your models here.
class query_form(models.Model):
    form_name = models.CharField(max_length=100,null=True)
    form_email = models.CharField(max_length=100,null=True)
    form_subject = models.CharField(max_length=100,null=True)
    form_message = models.CharField(max_length=1000,null=True)
    created = models.DateTimeField(auto_now_add=True,null=True)


    def __str__(self):
        return self.form_subject


class slider(models.Model):
    slider_name = models.CharField(null=True , max_length = 50 )
    slider_img = models.ImageField(upload_to='static/slider', null=True ,max_length = 100)
    Details = RichTextField(blank=True , null=True)
    
    def __str__(self):
        return self.slider_name
    
    
class q_form(models.Model):
    name = models.CharField(max_length=50,null=True)
    email = models.EmailField( max_length=254 , null=True) 
    phone = models.CharField(max_length=15 , null=True)
    message = models.CharField( max_length=500, null=True)
    subject = models.CharField(max_length=100,null=True)
       
       
class email_data(models.Model):
    email = models.EmailField( max_length=254 , null=True)       
    def __str__(self):
        return self.email


class blog(models.Model):
    blog_title = models.CharField(max_length=300, null=True)
    blog_img = models.ImageField(blank=True, upload_to='media')
    blog_desp = RichTextField()
    blog_date = models.DateField(auto_now_add=False)
    blog_author = models.CharField(max_length=30,null=True)
    blog_slug = AutoSlugField(populate_from='blog_title',unique=True ,default=None, blank=False, null=True)

class Course(models.Model):
    course_img = models.ImageField(upload_to='media', blank=False)
    course_bann = models.ImageField(upload_to='media', blank=False,null=True)
    course_price = models.CharField(max_length=6, null=True)
    course_title = models.CharField(max_length=50,null=True, blank=False)
    course_descp = RichTextField(blank=False, null=False)
    course_stu = models.CharField(max_length=5,null=True)
    course_lessons = models.CharField(max_length=4, null=True)
    course_slug = AutoSlugField(populate_from='course_title',unique=True ,default=None, blank=False, null=True)

class StuReview(models.Model):
    stu_name = models.CharField(max_length=40, null=True)
    stu_descp = models.CharField(max_length=500,null=True)

class Event(models.Model):
    event_title = models.CharField(max_length=200,null=True, blank=False)
    event_img = models.ImageField(upload_to='media', blank=False)
    event_descp = RichTextField(blank=False, null=False)
    event_date = models.DateField(auto_now_add=False)
    event_time = models.TimeField(auto_now_add=False)
    event_location = models.CharField(max_length=30,null=True)
    event_slug = AutoSlugField(populate_from='event_title',unique=True ,default=None, blank=False, null=True)

Teacher/models.py
from django.db import models

# Create your models here.

Home/views.py
from django.shortcuts import redirect, render,HttpResponseRedirect
from django.urls import reverse
from Student.forms import Student_detailForm
from Home.models import *
import sweetify
from django.views import View
from django.shortcuts import HttpResponse
from django.contrib import messages
# Create your views here.


def Home(request):
    course = Course.objects.all().order_by('id').reverse()[0:3]
    stur = StuReview.objects.all().order_by('id').reverse()
    eve = Event.objects.all().order_by('id').reverse()
    return render(request, 'Home/index.html',{'course':course,'stur':stur,'eve':eve})


def email_Data(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        emaildata = email_data.objects.create(email=email)
        emaildata.save()
        messages.info(request,"Successfully Submitted")
        # sweetify.success(request, 'Hey', text= 'You have successfully Subscribed', persistent='Done')
        return redirect('Home:Home')
        

def Addstudent(request):
    form = Student_detailForm()
    context = {
        'form':form
    }
    return render(request, 'Home/Addstudent.html' , context)
def About(request):
    return render(request, 'Home/about.html')

def ContactUs(request):
    if request.method == "POST":
        name = request.POST.get('name')
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        subject = request.POST.get('subject')
        qform = q_form.objects.create(name = name , email=email , phone = phone , message = message,subject=subject)
        qform.save()
        messages.info(request,"Successfully Submitted")
        # sweetify.success(request, 'Hey', text= 'You have successfully filled the form', persistent='Done')
        return HttpResponseRedirect(reverse('Home:ContactUs'))
    return render(request, 'Home/contactUs.html')

class blogpage(View):
    def get(self,request):
        bl = blog.objects.all()
        return render(request, 'Home/blog.html', {'bl':bl })

class blogdetailview(View):
    def get(self,request,slug):
        Blog = blog.objects.get(blog_slug=slug)
        Blog_object=blog.objects.get(blog_slug=slug)
        Blog_object.save()

        return render(request, 'Home/blogdetail.html',{'Blog':Blog})

class eventdetailview(View):
    def get(self,request,slug):
        event = Event.objects.get(event_slug=slug)
        event_object=Event.objects.get(event_slug=slug)
        event_object.save()

        return render(request, 'Home/eventdetail.html',{'event':event})

def TAC(request):
    return render(request, 'Home/titan.html')
def TAC2(request):
    return render(request, 'Home/TAC.html')

class allcourse(View):
    def get(self,request):
        course = Course.objects.all().order_by('id').reverse()[0:6]
        return render(request, 'Home/allcourse.html', {'course':course})

class coursedetailview(View):
    def get(self,request,slug):
        course = Course.objects.get(course_slug=slug)
        course_object=Course.objects.get(course_slug=slug)
        course_object.save()

        return render(request, 'Home/coursedetail.html',{'course':course})

def privacypol(request):
    return render(request, 'Home/privacypolicy.html')

Teacher/views.py
import email
from multiprocessing import context
from django import forms
from django.shortcuts import redirect, render
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from Admin.Leacturemodels import Lecture
from Admin.Lectureforms import LectureForm
from Admin.forms import CourseForm
from Admin.models import Course, UserProfile, newuserform
import sweetify

# Create your views here.
from django.contrib.auth.decorators import user_passes_test

from Student.forms import Student_detailForm

@user_passes_test(lambda u:u.is_staff, login_url=reverse_lazy('foo'))
def Profile(request):
    user = request.user
    if UserProfile.objects.filter(user = user).exists():
        data = UserProfile.objects.get(user = user)
        print(data)
        context = {
            'data': data
        }
    else:
        pass    
    return render(request, 'Teacher/Profile.html' , context)

@user_passes_test(lambda u:u.is_staff, login_url=reverse_lazy('foo'))
def Lectureboard(request):
    form = LectureForm()
    Lecture1 = Lecture.objects.all()
    # print(form)
    context = {
        'form': form,
        'Lecture':Lecture1,
    }
    return render(request , 'Teacher/Lectureboard.html' , context )
@user_passes_test(lambda u:u.is_staff, login_url=reverse_lazy('foo'))
def Courseboard(request):
    form = CourseForm()
    course = Course.objects.all()
    # print(form)
    context = {
        'form': form,
        'Course':course,
    }
    return render(request , 'Teacher/Courseboard.html' , context )
     
def edit_lecture(request , id ):
    item = Lecture.objects.get(id = id)
    form = LectureForm(instance=item)
    context = {
        'form' : form,
        'id':id,
        
        
    }
    return render(request , 'Teacher/Lecture_edit.html' , context )
         
def Course_edit(request , id ):
    item = Course.objects.get(id = id)
        
        
    form = CourseForm(instance=item)      



    context = {
        'form' : form,
        'id':id,
    }

    return render(request , 'Teacher/Course_edit.html' , context  )                         



def Addstudent(request):
    form = Student_detailForm()
    context = {
        'form':form
    }
    return render(request , 'Teacher/Addstudent.html' , context )
        
        
        
        



    

                            

templates/Teacher/Addstudent.html
{% extends 'Base/teacherbase.html' %} {% block body %}

<div class="container mt-3">
  <div class="card shadow-lg">
    <div class="card-header bg-info py-2 ">
      <h3 class="text-center fw-bold text-light mb-0">Add Student</h3>
    </div>
    <div class="card-body">
      <form enctype="multipart/form-data"  method="post" action="{% url 'Admin:ADDstudent' %}" >
        {% csrf_token %}
        <div class="row">
          {% for fm in form %}
    
          <div class="col-md-6 my-2">
            <p>{{fm.label_tag}}</p>
            {{ fm }} {{ fm.errors }}
          </div>
          {% endfor %}
        </div>
        <button type="submit" class="btn btn-dark mt-2 w-100">Submit</button>
      </form>
    </div>
    </div>
  </div>

{% endblock %}

templates/Teacher/Course_edit.html
{% extends 'Base/teacherbase.html' %} 
{% block body %}
<style>
  .django-ckeditor-widget textarea {
   width: 100%;
}
</style>

<div class="container mt-3">
  <div class="card shadow-lg">
    <div class="card-header bg-info">
      <h3 class="text-center mb-0 text-light">Edit Course</h3>
    </div>
    
    <div class="card-body">
      <form method="post" class="row" action="{% url 'Admin:Course_edit' id %}" >
        {% csrf_token %}
        <div class="row">
          {% for fm in form %}
    
          <div class="col-md-6 my-2">
            <p>{{fm.label_tag}}</p>
            {{ fm|safe }} {{ fm.errors }}
          </div>
          {% endfor %}
        </div>
    
        <button type="submit" class="btn btn-dark mt-2">Submit</button>
      </form>
    </div>
  </div>
</div>

 
{% endblock %}

templates/Teacher/Courseboard.html
{% extends 'Base/teacherbase.html' %} {% block body %}

  
<!-- new -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <!-- <form method="POST" enctype="multipart/form-data">{% csrf_token %}
          <input type="hidden" name="form" value="ADD">
          {{ form.media|safe}}
          {{ form.as_p|safe}}
        </form> -->
        <div class="card mt-3">
          <div class="card-header text-primary" >
            <ul class="nav nav-pills" id="myTab" role="tablist">
              <li class="nav-item" role="presentation">
                <button class="nav-link active" id="home-tab" data-bs-toggle="tab" data-bs-target="#home" type="button"
                  role="tab" aria-controls="home" aria-selected="true">List</button>
              </li>
              <li class="nav-item" role="presentation">
                <button class="nav-link" id="profile-tab" data-bs-toggle="tab" data-bs-target="#profile" type="button"
                  role="tab" aria-controls="profile" aria-selected="false">Manage</button>
              </li>
              <li class="nav-item" role="presentation">
                <button class="nav-link" id="contact-tab" data-bs-toggle="tab" data-bs-target="#contact" type="button"
                  role="tab" aria-controls="contact" aria-selected="false">Add</button>
              </li>
            </ul>
          </div>
          <!-- tab pane -->
          <div class="card-body">
            <div class="tab-content p-1">
              <div id="home" class="tab-pane fade show active" role="tabpanel" aria-labelledby="home-tab">
                <div class="table-responsive">
                  <table id="example2" class="table table-bordered table-striped">
                    <thead>
                      <tr>
                        <th>Course Name</th>
                        <th>Course title</th>
                        <th>Course Details</th>
                        <th>Course Price</th>
                  
                      </tr>
                    </thead>
                    <tbody>
                      {% for item in Course %}
                      <tr>
                        <td>{{item.Course_name}}</td>
                        <td>{{item.title}}</td>
                        <td>{{item.Details|safe}}</td>
                        <td>{{item.Price}}</td>
                  
                  
                  
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                </div>
              </div>

              <div id="profile" class="tab-pane fade" role="tabpanel" aria-labelledby="profile-tab">
                <div class="table-responsive">
                  <table id="example2" class="table table-bordered table-striped">
                    <thead>
                      <tr>
                          <th>Course Name</th>
                          <th>Course title</th>
                          <th>Course Details</th>
                          <th>Course Price</th>
                          <th>Edit</th>
                          <th>Delete</th>
                          {% comment %} <th>Number</th> {% endcomment %}
                        </tr>
                    </thead>
                    <tbody>
                      {% for item in Course %}
                      <tr>
                        <td>{{item.Course_name}}</td>
                        <td>{{item.title}}</td>
                        <td>{{item.Details|safe}}</td>
                        <td>{{item.Price}}</td>
                         <td><a href="{% url 'Teacher:TCourse_edit' item.id %}"><i class="mdi mdi-square-edit-outline"></i></a></td>
                         <td><span data-bs-toggle="modal" data-bs-target="#a{{item.id}}"><i class="mdi mdi-trash-can"></i></span></td>
                        <!-- /.modal  log out-->
                        <div id="a{{item.id}}" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
                          <div class="modal-dialog modal-top">
                              <div class="modal-content">
                                  <div class="modal-header">
                                      <h4 class="modal-title" id="topModalLabel">Course Delete</h4>
                                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-hidden="true"></button>
                                  </div>
                                  <form method = "POST" action="{% url 'Admin:Course_delete' item.id %}">
                                  <div class="modal-body">
                                      {% csrf_token %}
                                    <p class="text-danger fw-bold">Are you sure you want to delete course {{item.Course_name}}</p>
                                    </div>
                                    <div class="modal-footer">
                                      <a class="btn btn-info" data-bs-dismiss="modal">Close</a>
                                      <button type="submit" class="btn btn-danger">Delete</button>
                                    </div>
                                  </form>
                              </div><!-- /.modal-content -->
                        </div><!-- /.modal-dialog -->
                  
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                </div>

              </div>


              <div id="contact" class="tab-pane" role="tabpanel" aria-labelledby="contact-tab">
                <form  action="{% url 'Admin:Addcourse' %}" method="POST"  class="row">
                  {% csrf_token %}
                  <div class="row">
                    {% for fm in form %}
                
                    <div class="col-md-6 my-2">
                      <p>{{fm.label_tag}}</p>
                      {{ fm }} {{ fm.errors }}
                    </div>
                    {% endfor %}
                  </div>
                
                  <button type="submit" class="btn btn-dark mt-2">Submit</button>
                </form>
              </div>


            </div>




            <!-- /.card-header -->
            <!-- <div class="card-body"> -->

            <!-- </div> -->
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->
  </div>
  <!-- /.container-fluid -->



</section>
<!-- new -->



  {% endblock %}
  

templates/Teacher/Lecture_edit.html
{% extends 'Base/teacherbase.html' %} 

{% block body %}
<div class="container mt-3">
  <div class="card shadow-lg">
    <div class="card-header bg-info">
      <h3 class="text-center mb-0 text-light">Add Lecture</h3>
    </div>
    <div class="card-body">
      <form method="post" class="row" action="{% url 'Admin:Lecture_edit' id  %}">
        {% csrf_token %}
        <div class="row">
          {% for fm in form %}
    
          <div class="col-md-6 my-2">
            <p>{{fm.label_tag}}</p>
            {{ fm }} {{ fm.errors }}
          </div>
          {% endfor %}
        </div>
    
        <button type="submit" class="btn btn-dark mt-2">Submit</button>
      </form>
    </div>
  </div>
</div>

 
{% endblock %}

templates/Teacher/Lectureboard.html
{% extends 'Base/teacherbase.html' %} {% block body %}

  
<!-- new -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <!-- <form method="POST" enctype="multipart/form-data">{% csrf_token %}
          <input type="hidden" name="form" value="ADD">
          {{ form.media|safe}}
          {{ form.as_p|safe}}
        </form> -->
        <div class="card mt-3">
          <div class="card-header text-primary" >
            <ul class="nav nav-pills" id="myTab" role="tablist">
              <li class="nav-item" role="presentation">
                <button class="nav-link active" id="home-tab" data-bs-toggle="tab" data-bs-target="#home" type="button"
                  role="tab" aria-controls="home" aria-selected="true">List</button>
              </li>
              <li class="nav-item" role="presentation">
                <button class="nav-link" id="profile-tab" data-bs-toggle="tab" data-bs-target="#profile" type="button"
                  role="tab" aria-controls="profile" aria-selected="false">Manage</button>
              </li>
              <li class="nav-item" role="presentation">
                <button class="nav-link" id="contact-tab" data-bs-toggle="tab" data-bs-target="#contact" type="button"
                  role="tab" aria-controls="contact" aria-selected="false">Add</button>
              </li>
            </ul>
          </div>
          <!-- tab pane -->
          <div class="card-body">
            <div class="tab-content p-1">
              <div id="home" class="tab-pane fade show active" role="tabpanel" aria-labelledby="home-tab">
                <div class="table-responsive">
                  <table id="example2" class="table table-bordered table-striped">
                    <thead>
                      <tr>
                        <th>Lecture Number</th>
                        <th>Lecture week</th>
                        <th>Lecture title</th>
                        <th>Lecture Details</th>
                        <th>Course </th>
                  
                      </tr>
                    </thead>
                    <tbody>
                      {% for item in Lecture %}
                      <tr>
                        <td>{{item.lecture_num}}</td>
                        <td>{{item.week_num}}</td>
                        <td>{{item.title}}</td>
                        <td>{{item.description|safe}}</td>
                        <td>{{item.course}}</td>
                  
                  
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                </div>
              </div>

              <div id="profile" class="tab-pane fade" role="tabpanel" aria-labelledby="profile-tab">
                <div class="table-responsive">
                  <table id="example2" class="table table-bordered table-striped">
                    <thead>
                      <tr>
                        <th>Lecture Number</th>
                        <th>Lecture week</th>
                        <th>Lecture title</th>
                        <th>Lecture Details</th>
                        <th>Course </th>
                        <th>Edit</th>
                        <th>Delete</th>
                      </tr>
                    </thead>
                    <tbody>
                      {% for item in Lecture %}
                      <tr>
                        <td>{{item.lecture_num}}</td>
                        <td>{{item.week_num}}</td>
                        <td>{{item.title}}</td>
                        <td>{{item.description|safe}}</td>
                        <td>{{item.course}}</td>
                        <td><a href="{% url 'Teacher:TLecture_edit' item.id  %}"><i class="mdi mdi-square-edit-outline"></i></a></td>
                        <td><span data-bs-toggle="modal" data-bs-target="#a{{item.id}}"><i class="mdi mdi-trash-can"></i></span></td>
                        <!-- /.modal  log out-->
                        <div id="a{{item.id}}" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
                          <div class="modal-dialog modal-top">
                              <div class="modal-content">
                                  <div class="modal-header">
                                      <h4 class="modal-title" id="topModalLabel">Lecture Delete</h4>
                                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-hidden="true"></button>
                                  </div>
                                  <form method = "POST" action="{% url 'Admin:Leature_delete' item.id %}">
                                  <div class="modal-body">
                                      {% csrf_token %}
                                    <p class="text-danger fw-bold">Are you sure you want to delete Lecture {{item.title}}</p>
                                    </div>
                                    <div class="modal-footer">
                                      <a class="btn btn-info" data-bs-dismiss="modal">Close</a>
                                      <button type="submit" class="btn btn-danger">Delete</button>
                                    </div>
                                  </form>
                              </div><!-- /.modal-content -->
                        </div><!-- /.modal-dialog -->
                  
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                </div>

              </div>


              <div id="contact" class="tab-pane" role="tabpanel" aria-labelledby="contact-tab">
                <form  action="{% url 'Admin:Addlecture' %}" method="POST"  class="row">
                  {% csrf_token %}
                  <div class="row">
                    {% for fm in form %}
                
                    <div class="col-6 my-2">
                      <p>{{fm.label_tag}}</p>
                      {{ fm }} {{ fm.errors }}
                    </div>
                    {% endfor %}
                  </div>
                
                  <button type="submit" class="btn btn-dark mt-2">Submit</button>
                </form>
              </div>


            </div>




            <!-- /.card-header -->
            <!-- <div class="card-body"> -->

            <!-- </div> -->
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->
  </div>
  <!-- /.container-fluid -->



</section>
<!-- new -->



  {% endblock %}
  

templates/Teacher/Student_edit.html
{% extends 'Base/teacherbase.html' %} 
{% block body %}
<p class="text-center fw-bold bg-info py-2 text-light">Update Student</p>

<form enctype="multipart/form-data" method="post" class="row" action="{% url 'Admin:Student_edit' id %}">
  {% csrf_token %}
  <div class="row">
    {% for fm in form %}

    <div class="col-6 my-2">
      <p>{{fm.label_tag}}</p>
      {{ fm }} {{ fm.errors }}
    </div>
    {% endfor %}
  </div>

  <button type="submit" class="btn btn-dark mt-2">Submit</button>
  <a href="{% url 'Admin:Studentboard' %}" class="btn btn-dark mt-2">Cancel</a>
</form>

 
{% endblock %}